config/routes.rb
Rails.application.routes.draw do
  resources :document_categories

  resources :documents

  resources :activity_categories

  resources :issues

  resources :activities

  resources :project_teams

  resources :projects

  devise_for :users

  get 'home/index'

  get 'documents/:documentCategoryId/:projectId' => 'documents#show'
  get 'activities/:projectId' =>'documents#show'
  get 'projects/:projectId' => 'activities#index'
  get 'projects/:projectId' => 'documents#index'
  get 'projects/:projectId' => 'project_teams#index'

  devise_scope :user do
    authenticated :user do
      root 'projects#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :activity
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @project = Project.find(params[:projectId])
    @issues = Issue.where('project_id = ?', params[:projectId]).order('created_at DESC')
    #@acivity = Activity.find(params[:projectId])
    #@issues = Issue.find(@activity.id)
    @issue = Issue.new
    respond_with(@issues)
  end

  def show
    respond_with(@issue)
  end

  def new
    @issue = Issue.new
    respond_with(@issue)
  end

  def edit
  end

  def create
    @issue = Issue.new
    @issue.issueName = params[:issue][:issueName]
    @issue.project_id = params[:issue][:project_id]
    @issue.save
      Notification.issue_creation_notification(@issue).deliver
    redirect_to issues_path(projectId: params[:issue][:projectId])
    #respond_with(@issue)
  end

  def update
    @issue.update(issue_params)
    respond_with(@issue)
  end

  def destroy
    @issue.destroy
    respond_with(@issue)
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:issueId, :issueName, :project_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :issueName %></div>
    <div class="col-lg-9"><%= f.text_field :issueName, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"></div>
    <div class="col-lg-9"><%= f.submit "Create Issue", :class => "btn btn-default" %> &nbsp;&nbsp;
    <%= link_to 'Back', issues_path, :class => "btn btn-default" %></div>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<div id="new_project" class="col-md-4">
  <div class="container">
    <div class="page-header">
      <h1><%= @project.projectName %>: Issues</h1>
    </div>
    <br/>
    <div class="row">
      <table class="table">
        <thead>
        <tr>
          <th>Issuename</th>
        </tr>
        </thead>
        <tbody>
        <% @issues.each do |issue| %>
            <tr>
              <td><%= link_to issue.issueName, issue %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
      <br>
      <div class="col-lg-10 text-right">
        <!-- Button trigger modal -->
            <% link_to "New Isuue", new_issue_path(:projectId  => params[:projectId]), :class => "btn btn-success" %>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
              Create Issues
            </button> |
      </div>
        <%= link_to 'Back', projects_path, :class => "btn btn-default" %>
   </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="z-index: 99999;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Create Issue</h3>
      </div>

      <div class="modal-body">

        <%= form_for(@issue) do |f| %>
          <% if @issue.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

              <ul>
              <% @issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.hidden_field :project_id, :value => @project.id %>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :issueName %></div>
            <div class="col-lg-6"><%= f.text_field :issueName, :class => "form-control" %></div>
          </div>
          <div class="form-group">
            <div class="col-lg-6"></div>
            <div class="col-lg-6"><%= f.submit "Create Issue", :class => "btn btn-default" %></div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/issues/new.html.erb
<div class="container">
  <div class="page-header">
<h1>New issue</h1>
</div>
<%= render 'form' %>
</div>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issueid:</strong>
  <%= @issue.id %>
</p>

<p>
  <strong>Issuename:</strong>
  <%= @issue.issueName %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>