config/routes.rb
Rails.application.routes.draw do
  resources :document_categories

  resources :documents

  resources :activity_categories

  resources :issues

  resources :activities

  resources :project_teams

  resources :projects

  devise_for :users

  get 'home/index'

  get 'documents/:documentCategoryId/:projectId' => 'documents#show'
  get 'activities/:projectId' =>'documents#show'
  get 'projects/:projectId' => 'activities#index'
  get 'projects/:projectId' => 'documents#index'
  get 'projects/:projectId' => 'project_teams#index'

  devise_scope :user do
    authenticated :user do
      root 'projects#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_teams
  has_many :users, through: :project_teams
  has_many :activities

  before_save :capitalizeProjectName

  def capitalizeProjectName
    self.projectName.upcase!
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @project = Project.new

    if params[:search]
      @projects = Project.where("\"projectName\" like (?)", "%#{params[:search].upcase}%")
    else
      @user = User.find(current_user.id)
      @projects = @user.projects.all.order('created_at DESC')
      respond_with(@projects)
    end

  end

  def show
    @projectTeam = ProjectTeam.new
    @projectTeamList = User.all.where.not(id: @project.users.collect { |u| u.id } )
    #respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save

    @project.project_teams.create(:user_id => current_user.id ,:project_id => @project.id)

    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:projectName, :description, :startDate, :endDate)
    end
    def collection_ids
      params.require(:project).permit(:user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <div class="col-lg-3"><%= f.label :projectName %></div>
      <div class="col-lg-9"><%= f.text_field :projectName, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :description %></div>
    <div class="col-lg-9"><%= f.text_area :description, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :startDate %></div>
    <div class="col-lg-9"><%= f.date_select :startDate, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :endDate %></div>
    <div class="col-lg-9"><%= f.date_select :endDate, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"></div>
    <div class="col-lg-9 text-right">
        <%= f.submit "Create Project", :class => "btn btn-default" %> &nbsp;&nbsp;
        <%= link_to 'Back', projects_path, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<script>

$(document).ready(function() {
$('#myModal').appendTo("body");
});

</script>

<div id="all_projects" class="col-md-6">
  <div class="container">
    <div class="page-header">
      <h1>Listing projects</h1>
    </div>
    <%= form_tag projects_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "search"%>
        </p>
    <% end %>
    <br/>
    <div class="row">
      <table class="table table-bordered">
        <thead>
        <tr>
          <th>Projectname</th>
          <th>Startdate</th>
          <th>Enddate</th>
        </tr>
        </thead>

        <tbody>
        <% @projects.each do |project| %>
            <tr>
              <td><%= link_to project.projectName, project %></td>
              <td><%= project.startDate %></td>
              <td><%= project.endDate %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <% if current_user.role_id == 1 %>
          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
            New Project
          </button>
      <% end %>
    </div>
  </div>
  <br>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="z-index: 99999;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Create Project</h3>
      </div>

      <div class="modal-body">

        <%= form_for(@project) do |f| %>
            <% if @project.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

                  <ul>
                    <% @project.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="form-group">
              <div class="col-lg-6"><%= f.label :projectName %></div>
              <div class="col-lg-6"><%= f.text_field :projectName, :class => "form-control" %></div>
            </div>
            <div class="form-group">
              <div class="col-lg-6"><%= f.label :description %></div>
              <div class="col-lg-6"><%= f.text_area :description, :class => "form-control" %></div>
            </div>
            <div class="form-group">
              <div class="col-lg-6"><%= f.label :startDate %></div>
              <div class="col-lg-6"><%= f.date_select :startDate, :class => "form-control" %></div>
            </div>
            <div class="form-group">
              <div class="col-lg-6"><%= f.label :endDate %></div>
              <div class="col-lg-6"><%= f.date_select :endDate, :class => "form-control" %></div>
            </div>
            <div class="form-group">
              <div class="col-lg-6"></div>
              <div class="col-lg-6 text-right">
                <%= f.submit "Create Project", :class => "btn btn-success" %>
              </div>
            </div>
        <% end %>
      </div>

      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-header">
<h1>New project</h1>
</div>
<br/>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<script>

$(document).ready(function() {
    $('#myModal').appendTo("body");
});

</script>



<div id="project Details" class="col-md-4">
  <h3>Project :<%= @project.projectName %></h3><br/>
  <table class = "table table-striped">
    <tr>
      <td><h4><%= link_to "Documents", documents_path(:projectId => @project.id) %></h4></td>
    </tr>
    <tr>
      <td><h4><%= link_to "Activities", activities_path(:projectId => @project.id) %></h4></td>
    </tr>
    <tr>
      <td><h4><%= link_to "Issues", issues_path(:projectId => @project.id) %></h4></td>
    </tr>
 </table>
</div>

<div id="project" class="col-md-6">
   <h4>Project Details </h4>
  <table class="table table-bordered">
    <tr class="success">
      <th>Description</th>
      <td><%= @project.description %></td>
    </tr>
    <tr class="info">
      <th>Start Date:</th>
      <td><%= @project.startDate %></td>
    </tr>
    <tr class="warning">
      <th>Expected Completion Date:</th>
      <td><%= @project.endDate %></td>
    </tr>
  </table>
  <br/>
  <div class="col-lg-12 text-right"><%= link_to 'Edit Project Details', edit_project_path(@project), :class => "btn btn-default" %> |
    <%= link_to 'Project List', projects_path, :class => "btn btn-info" %></div>
  <br/>
  <h4>Project Team </h4>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <% @project.users.each do |team| %>
        <tr>
          <td><%= team.firstName %>&nbsp&nbsp<%= team.lastName %></td>
          <td><%= team.email %></td>
        </tr>
    <% end %>
</tbody>
</table>
<br/>
  <% if current_user.role_id == 1 %>
    <div class="col-lg-12 text-right">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
        Add Team Member
      </button>
    </div>
  <% end %>
<br/>


</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="z-index: 99999;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Select the Project Team</h3>
      </div>

      <div class="modal-body">

        <%= form_for(@projectTeam) do |f| %>
            <div class="form-group">
              <%= f.hidden_field :project_id, :value => @project.id %>
              <div class="col-lg-6"><%= f.label :Team_Members %></div>
              <div class="col-lg-6"><%= f.collection_select :user_id, @projectTeamList, :id, :email %></div>
            </div>
            <br/>
            <div class="form-group">
              <div class="col-lg-6"></div>
              <div class="col-lg-6"><%= f.submit "Add Member", :class => "btn btn-success" %></div>
            </div>
            <br />
            <% end %>
      </div>

      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>