config/routes.rb
Rails.application.routes.draw do
  resources :document_categories

  resources :documents

  resources :activity_categories

  resources :issues

  resources :activities

  resources :project_teams

  resources :projects

  devise_for :users

  get 'home/index'

  get 'documents/:documentCategoryId/:projectId' => 'documents#show'
  get 'activities/:projectId' =>'documents#show'
  get 'projects/:projectId' => 'activities#index'
  get 'projects/:projectId' => 'documents#index'
  get 'projects/:projectId' => 'project_teams#index'

  devise_scope :user do
    authenticated :user do
      root 'projects#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
  has_many :activities
end

app/controllers/activity_categories_controller.rb
class ActivityCategoriesController < ApplicationController
  before_action :set_activity_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @activity_categories = ActivityCategory.all
    respond_with(@activity_categories)
  end

  def show
    respond_with(@activity_category)
  end

  def new
    @activity_category = ActivityCategory.new
    respond_with(@activity_category)
  end

  def edit
  end

  def create
    @activity_category = ActivityCategory.new(activity_category_params)
    @activity_category.save
    respond_with(@activity_category)
  end

  def update
    @activity_category.update(activity_category_params)
    respond_with(@activity_category)
  end

  def destroy
    @activity_category.destroy
    respond_with(@activity_category)
  end

  private
    def set_activity_category
      @activity_category = ActivityCategory.find(params[:id])
    end

    def activity_category_params
      params.require(:activity_category).permit(:categoryId, :categoryName)
    end
end

app/helpers/activity_categories_helper.rb
module ActivityCategoriesHelper
end

app/views/activity_categories/_form.html.erb
<%= form_for(@activity_category) do |f| %>
  <% if @activity_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_category.errors.count, "error") %> prohibited this activity_category from being saved:</h2>

      <ul>
      <% @activity_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoryId %><br>
    <%= f.text_field :categoryId %>
  </div>
  <div class="field">
    <%= f.label :categoryName %><br>
    <%= f.text_field :categoryName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_categories/edit.html.erb
<h1>Editing activity_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_category %> |
<%= link_to 'Back', activity_categories_path %>

app/views/activity_categories/index.html.erb
<h1>Listing activity_categories</h1>

<table>
  <thead>
    <tr>
      <th>Categoryid</th>
      <th>Categoryname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_categories.each do |activity_category| %>
      <tr>
        <td><%= activity_category.categoryId %></td>
        <td><%= activity_category.categoryName %></td>
        <td><%= link_to 'Show', activity_category %></td>
        <td><%= link_to 'Edit', edit_activity_category_path(activity_category) %></td>
        <td><%= link_to 'Destroy', activity_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity category', new_activity_category_path %>

app/views/activity_categories/new.html.erb
<h1>New activity_category</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_categories_path %>

app/views/activity_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categoryid:</strong>
  <%= @activity_category.categoryId %>
</p>

<p>
  <strong>Categoryname:</strong>
  <%= @activity_category.categoryName %>
</p>

<%= link_to 'Edit', edit_activity_category_path(@activity_category) %> |
<%= link_to 'Back', activity_categories_path %>