config/routes.rb
Rails.application.routes.draw do
  resources :document_categories

  resources :documents

  resources :activity_categories

  resources :issues

  resources :activities

  resources :project_teams

  resources :projects

  devise_for :users

  get 'home/index'

  get 'documents/:documentCategoryId/:projectId' => 'documents#show'
  get 'activities/:projectId' =>'documents#show'
  get 'projects/:projectId' => 'activities#index'
  get 'projects/:projectId' => 'documents#index'
  get 'projects/:projectId' => 'project_teams#index'

  devise_scope :user do
    authenticated :user do
      root 'projects#index', as: :authenticated_root
    end
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :project
  belongs_to :activity_category
  belongs_to :user
  has_many :issues
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @project = Project.find(params[:projectId])
    @user = @project.users
    @activity = Activity.new
    @allactivities = Activity.where('project_id = ?', params[:projectId])
    @activities = Activity.where('project_id = ?  AND user_id= ?', params[:projectId], current_user.id )
    respond_with(@activities)
  end

  def show
    respond_with(@activity)
  end

  def new
    @project = Project.find(params[:projectId])
    @user = @project.users
    @activity = Activity.new
    respond_with(@activity)
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.assignerID = current_user.id
    @activity.priority = params[:priority]
    @activity.save
    redirect_to activities_path(:projectId => params[:activity][:project_id])
  end

  def update
    @activity.update(activity_params)
    respond_with(@activity)
  end

  def destroy
    @activity.destroy
    respond_with(@activity)
  end

  private
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:activityId, :activityName, :status, :activity_category_id, :documentcategories_id, :dueDate,:priority, :user_id, :project_id, :projectId)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :project_id, :value => @project.id %>
  <%= f.hidden_field :status, :value => "Incomplete" %>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :activityName %></div>
    <div class="col-lg-9"><%= f.text_field :activityName, :class => "form-control" %></div>
  </div>
<br/>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :Activity_Category %></div>
    <div class="col-lg-9"><%= f.collection_select :activity_category_id, ActivityCategory.all, :id, :activityCategoryName %></div>
  </div>
  <br/>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :Document_Category %></div>
    <div class="col-lg-9"><%= f.collection_select :documentcategories_id, DocumentCategory.all, :id, :categoryName %></div>
  </div>
  <br/>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :DueDate %></div>
    <div class="col-lg-9"><%= f.date_select :dueDate, :class => "form-control" %></div>
  </div>
  <br/>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :Priority %></div>
    <div class="col-lg-9">
      <%= radio_button_tag(:priority, "Low", checked = true) %><%= label_tag(:priority, "Low") %> &nbsp&nbsp&nbsp&nbsp
      <%= radio_button_tag(:priority, "Medium", checked = false) %><%= label_tag(:priority, "Medium") %> &nbsp&nbsp&nbsp&nbsp
      <%= radio_button_tag(:priority, "High", checked = false) %><%= label_tag(:priority, "High") %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"><%= f.label :Assigned_To %></div>
    <div class="col-lg-9"><%= f.collection_select :user_id, @user, :id, :email %></div>
  </div>
  <div class="form-group">
    <div class="col-lg-3"></div>
    <div class="col-lg-9"><%= f.submit "Create Activity", :class => "btn btn-default" %> &nbsp;&nbsp;
    <%= link_to 'Back', activities_path, :class => "btn btn-default" %></div>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div id="all_projects" class="col-md-4">
  <div class="container">
    <div class="page-header">
      <h1><%= @project.projectName %> :Activity List</h1>
    </div>
    <br/>
    <div class="row">
      <table class="table">
        <thead>
        <tr>
          <th>Activityname</th>
          <th>Status</th>
          <th>Due Date</th>
          <th>Priority</th>
        </tr>
        </thead>

        <tbody>
        <% if current_user.role_id == 1 %>
          <% @allactivities.each do |activity| %>
            <tr>
              <td><%= link_to activity.activityName, document_path(:id =>activity.project_id, :projectId => activity.project_id, :documentCategoryId => activity.documentcategories_id)%></td>
              <td><%= activity.status %></td>
              <td><%= activity.dueDate %></td>
              <td><%= activity.priority %></td>
            </tr>
          <% end %>
        <% else %>
          <% @activities.each do |activity| %>
            <tr>
              <td><%= link_to activity.activityName, document_path(:id =>activity.project_id, :projectId => activity.project_id, :documentCategoryId => activity.documentcategories_id)%></td>
              <td><%= activity.status %></td>
              <td><%= activity.dueDate %></td>
              <td><%= activity.priority %></td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
      <br/>
      <div class="col-lg-10 text-right">
        <% if current_user.role_id == 1 %>
        <!-- Button trigger modal -->
            <% link_to "Create Activity", new_activity_path(:projectId  => params[:projectId]), :class => "btn btn-success" %>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">
              Create Activity
            </button> |
          </div>
        <% end %>
        <%= link_to 'Back To Project', project_path(:id =>params[:projectId]), :class => "btn btn-default" %> </div>
      <br/>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="z-index: 99999;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Create Activity</h3>
      </div>

      <div class="modal-body">

        <%= form_for(@activity) do |f| %>
          <% if @activity.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

              <ul>
              <% @activity.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.hidden_field :project_id, :value => @project.id %>
          <%= f.hidden_field :status, :value => "Incomplete" %>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :activityName %></div>
            <div class="col-lg-6"><%= f.text_field :activityName, :class => "form-control" %></div>
          </div>
        <br/>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :Activity_Category %></div>
            <div class="col-lg-6"><%= f.collection_select :activity_category_id, ActivityCategory.all, :id, :activityCategoryName %></div>
          </div>
          <br/>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :Document_Category %></div>
            <div class="col-lg-6"><%= f.collection_select :documentcategories_id, DocumentCategory.all, :id, :categoryName %></div>
          </div>
          <br/>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :DueDate %></div>
            <div class="col-lg-6"><%= f.date_select :dueDate, :class => "form-control" %></div>
          </div>
          <br/>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :Priority %></div>
            <div class="col-lg-6">
              <%= radio_button_tag(:priority, "Low", checked = true) %><%= label_tag(:priority, "Low") %> &nbsp
              <%= radio_button_tag(:priority, "Medium", checked = false) %><%= label_tag(:priority, "Medium") %> &nbsp
              <%= radio_button_tag(:priority, "High", checked = false) %><%= label_tag(:priority, "High") %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-6"><%= f.label :Assigned_To %></div>
            <div class="col-lg-6"><%= f.collection_select :user_id, @user, :id, :email %></div>
          </div>
          <div class="form-group">
            <div class="col-lg-6"></div>
            <div class="col-lg-6"><%= f.submit "Create Activity", :class => "btn btn-success" %></div>
          </div>
        <% end %>
      </div>

      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="page-header">
<h1>New activity</h1>
</div>
<%= render 'form' %>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activityid:</strong>
  <%= @activity.id %>
</p>

<p>
  <strong>Activityname:</strong>
  <%= @activity.activityName %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>